apiVersion: v2
name: edge-dispatch
description: Edge Dispatch Framework - Edge content delivery and acceleration
type: application
version: 0.6.0
appVersion: "0.6.0"
keywords:
  - cdn
  - edge-computing
  - content-delivery
  - dispatch
  - streaming
home: https://github.com/im10furry/edge-dispatch-framework
sources:
  - https://github.com/im10furry/edge-dispatch-framework
maintainers:
  - name: im10furry
    email: dev@im10furry.com
