apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-dispatch.fullname" . }}-secrets
  labels:
    {{- include "edge-dispatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.controlPlane.enabled }}
  cp-token-secret: {{ .Values.controlPlane.env.tokenSecret | quote }}
  cp-admin-jwt-secret: {{ .Values.controlPlane.env.adminJwtSecret | quote }}
  cp-admin-access-key: {{ .Values.controlPlane.env.adminAccessKey | quote }}
  cp-admin-secret-key: {{ .Values.controlPlane.env.adminSecretKey | quote }}
  {{- end }}
  {{- if .Values.gateway.enabled }}
  gw-auth-token: {{ .Values.gateway.env.authToken | quote }}
  gw-cp-token: {{ .Values.gateway.env.cpToken | quote }}
  {{- end }}
  {{- if .Values.edgeAgent.enabled }}
  ea-node-token: {{ .Values.edgeAgent.env.nodeToken | quote }}
  ea-tunnel-auth-token: {{ .Values.edgeAgent.env.tunnelAuthToken | quote }}
  {{- end }}
  {{- if .Values.dnsAdapter.enabled }}
  dns-token-secret: {{ .Values.dnsAdapter.env.tokenSecret | quote }}
  {{- end }}
  {{- if .Values.postgres.enabled }}
  pg-user: {{ .Values.postgres.env.user | quote }}
  pg-password: {{ .Values.postgres.env.password | quote }}
  pg-database: {{ .Values.postgres.env.database | quote }}
  {{- end }}
